# Generated by Django 5.1.11 on 2025-08-11 12:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assessments", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="difficulty",
            field=models.CharField(
                choices=[("easy", "ساده"), ("medium", "متوسط"), ("hard", "سخت")],
                default="medium",
                max_length=6,
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="explanation",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="question",
            name="target_level",
            field=models.CharField(
                choices=[
                    ("A1", "A1"),
                    ("A2", "A2"),
                    ("B1", "B1"),
                    ("B2", "B2"),
                    ("C1", "C1"),
                ],
                default="A1",
                max_length=2,
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="type",
            field=models.CharField(
                choices=[("mcq", "چهارگزینه\u200cای"), ("fill", "جای خالی")],
                default="mcq",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="weight",
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="submission",
            name="score",
            field=models.FloatField(default=0),
        ),
        migrations.CreateModel(
            name="AnswerPattern",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pattern", models.CharField(max_length=200)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("exact", "مطابقت دقیق"),
                            ("icase", "بدون حساسیت به حروف"),
                            ("regex", "عبارت باقاعده"),
                        ],
                        default="icase",
                        max_length=10,
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answer_patterns",
                        to="assessments.question",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SubmissionItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("selected_choice_id", models.IntegerField(blank=True, null=True)),
                ("user_text", models.CharField(blank=True, max_length=300)),
                ("is_correct", models.BooleanField(default=False)),
                ("gained_score", models.FloatField(default=0)),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="assessments.question",
                    ),
                ),
                (
                    "submission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="assessments.submission",
                    ),
                ),
            ],
        ),
    ]
