# Generated by Django 5.1.11 on 2025-08-11 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assessments", "0002_question_difficulty_question_explanation_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="submission",
            name="email",
            field=models.EmailField(blank=True, max_length=254, verbose_name="ایمیل"),
        ),
        migrations.AddField(
            model_name="submission",
            name="full_name",
            field=models.CharField(blank=True, max_length=150, verbose_name="نام"),
        ),
    ]
