# Generated by Django 5.1.11 on 2025-08-11 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assessments", "0003_submission_email_submission_full_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="assessment",
            name="attempt_limit",
            field=models.PositiveSmallIntegerField(
                default=3, verbose_name="حداکثر دفعات تلاش"
            ),
        ),
        migrations.AddField(
            model_name="assessment",
            name="time_limit_seconds",
            field=models.PositiveIntegerField(
                default=600, verbose_name="مهلت پاسخ (ثانیه)"
            ),
        ),
        migrations.AddField(
            model_name="submission",
            name="duration_seconds",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="submission",
            name="ratio",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="submission",
            name="total_weight",
            field=models.FloatField(default=0),
        ),
    ]
