# Generated by Django 5.1.11 on 2025-08-11 13:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assessments", "0004_assessment_attempt_limit_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="correct_boolean",
            field=models.BooleanField(
                blank=True, null=True, verbose_name="پاسخ صحیح (برای درست/نادرست)"
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="type",
            field=models.CharField(
                choices=[
                    ("mcq", "چهارگزینه\u200cای"),
                    ("fill", "جای خالی"),
                    ("multi", "چندگزینه\u200cای (چند پاسخ)"),
                    ("tf", "درست/نادرست"),
                    ("order", "ترتیب\u200cدهی"),
                    ("match", "تطبیق"),
                ],
                default="mcq",
                max_length=10,
            ),
        ),
        migrations.CreateModel(
            name="MatchPair",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("left_text", models.CharField(max_length=200)),
                ("right_text", models.CharField(max_length=200)),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="match_pairs",
                        to="assessments.question",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OrderingItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.CharField(max_length=200)),
                ("correct_position", models.PositiveSmallIntegerField()),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ordering_items",
                        to="assessments.question",
                    ),
                ),
            ],
            options={
                "ordering": ["correct_position"],
            },
        ),
    ]
