# Generated by Django 5.1.11 on 2025-08-13 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assessments", "0005_question_correct_boolean_alter_question_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="type",
            field=models.CharField(
                choices=[
                    ("mcq", "چهارگزینه\u200cای"),
                    ("multi", "چندگزینه\u200cای (چند پاسخ)"),
                    ("tf", "درست/نادرست"),
                    ("fill", "جای خالی"),
                    ("order", "ترتیب\u200cدهی"),
                    ("match", "تطبیق"),
                ],
                default="mcq",
                max_length=10,
            ),
        ),
    ]
