"""
Django settings for sami project.

Generated by 'django-admin startproject' using Django 5.1.11.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os
import environ

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Environment
env = environ.Env(
    DEBUG=(bool, True),
)
environ.Env.read_env(os.path.join(BASE_DIR, ".env"))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env.bool("DEBUG", default=False)

# SECURITY WARNING: keep the secret key used in production secret!
# در production حتماً SECRET_KEY را در .env تنظیم کنید
if DEBUG:
    SECRET_KEY = env("SECRET_KEY", default="django-insecure-dev-secret-key")
else:
    SECRET_KEY = env("SECRET_KEY", default=None)
    if not SECRET_KEY:
        raise ValueError("SECRET_KEY environment variable must be set in production")

# ALLOWED_HOSTS: در production فقط domain واقعی را اضافه کنید
if DEBUG:
    ALLOWED_HOSTS = env.list("ALLOWED_HOSTS", default=["localhost", "127.0.0.1"])
else:
    ALLOWED_HOSTS = env.list("ALLOWED_HOSTS", default=["samideutsch.ir", "www.samideutsch.ir"])
    if not ALLOWED_HOSTS:
        raise ValueError("ALLOWED_HOSTS must be set in production") 


# Application definition

INSTALLED_APPS = [
    # Django core
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.sitemaps",

    # Third-party
    "crispy_forms",
    "crispy_bootstrap5",
    "django_filters",
    "payments",

    # Local apps
    "core",
    "courses",
    "blog",
    "shop",
    "accounts",
    "search",
    "assessments",
    "siteconfig",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "accounts.middleware.SecurityLoggingMiddleware",  # Security logging
    "sami.security_middleware.SecurityHeadersMiddleware",  # Additional security headers
    "sami.security_middleware.SessionSecurityMiddleware",  # Session security
    "core.middleware.SiteAnalyticsMiddleware",  # Site visits analytics
    # "sami.security_middleware.IPWhitelistMiddleware",  # Uncomment to enable IP whitelist for admin
]

ROOT_URLCONF = "sami.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "siteconfig.context_processors.site_settings",
            ],
        },
    },
]

WSGI_APPLICATION = "sami.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

# Database
try:
    DATABASES = {
        "default": env.db(
            "DATABASE_URL",
            default=f"sqlite:///{BASE_DIR / 'db.sqlite3'}",
        )
    }
    
    # Fix PostgreSQL connection issues:
    # 1. Force IPv4 instead of IPv6 (localhost -> 127.0.0.1)
    # 2. Enable SSL for secure connections
    if DATABASES.get("default") and "postgresql" in DATABASES["default"].get("ENGINE", "").lower():
        # Replace localhost with 127.0.0.1 to force IPv4
        if DATABASES["default"].get("HOST") == "localhost":
            DATABASES["default"]["HOST"] = "127.0.0.1"
        
        # Add SSL options for PostgreSQL
        DATABASES["default"]["OPTIONS"] = {
            **DATABASES["default"].get("OPTIONS", {}),
            "sslmode": "prefer",  # Try SSL, fallback to non-SSL if not available
        }
        
except Exception as e:
    if not DEBUG:
        raise ValueError(f"DATABASE_URL is required in production. Error: {e}")
    raise

# Validation: allow SQLite even when DEBUG=False (use at your own risk)
if not DATABASES.get("default") or not DATABASES["default"].get("ENGINE"):
    raise ValueError("A valid database configuration is required")


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
        "OPTIONS": {
            "min_length": 8,
        },
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


############################
# Time Zone
############################

TIME_ZONE = env("TIME_ZONE", default="UTC")
USE_TZ = True


############################
# Static & Media files
# https://docs.djangoproject.com/en/5.1/howto/static-files/
############################

STATIC_URL = "/static/"
STATICFILES_DIRS = [BASE_DIR / "static"]
STATIC_ROOT = BASE_DIR / "staticfiles"

MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

############################
# Crispy Forms
############################

CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"
CRISPY_TEMPLATE_PACK = "bootstrap5"



############################
# Search / MeiliSearch
############################

MEILI_URL = env("MEILI_URL", default="http://127.0.0.1:7700")
MEILI_API_KEY = env("MEILI_API_KEY", default=None)

############################
# Payments (django-payments) - configure providers via env
############################

PAYMENTS_VARIANTS = {
    # Example variants; provide proper keys in .env for real use
    # "stripe": ("payments.stripe.StripeProvider", {
    #     "secret_key": env("STRIPE_SECRET_KEY", default=""),
    #     "public_key": env("STRIPE_PUBLIC_KEY", default=""),
    #     "store_name": env("STORE_NAME", default="Sami Language"),
    #     "store_image": None,
    # }),
    # "paypal": ("payments.paypal.PaypalProvider", {
    #     "client_id": env("PAYPAL_CLIENT_ID", default=""),
    #     "secret": env("PAYPAL_SECRET", default=""),
    #     "endpoint": env("PAYPAL_ENDPOINT", default="https://api-m.sandbox.paypal.com"),
    # }),
    # Development dummy provider
    "dummy": ("payments.dummy.DummyProvider", {}),
}

# django-payments host settings (development)
PAYMENT_HOST = env("PAYMENT_HOST", default="127.0.0.1:8000")
PAYMENT_USES_HTTPS = env.bool("PAYMENT_USES_HTTPS", default=False)

############################
# Email Configuration
############################

EMAIL_BACKEND = env(
    "EMAIL_BACKEND",
    default="django.core.mail.backends.console.EmailBackend" if DEBUG else "django.core.mail.backends.smtp.EmailBackend",
)

# SMTP Settings (برای production)
EMAIL_HOST = env("EMAIL_HOST", default="")
EMAIL_PORT = env.int("EMAIL_PORT", default=587)
EMAIL_USE_TLS = env.bool("EMAIL_USE_TLS", default=True)
EMAIL_USE_SSL = env.bool("EMAIL_USE_SSL", default=False)
EMAIL_HOST_USER = env("EMAIL_HOST_USER", default="")
EMAIL_HOST_PASSWORD = env("EMAIL_HOST_PASSWORD", default="")
DEFAULT_FROM_EMAIL = env("DEFAULT_FROM_EMAIL", default="noreply@samideutsch.ir")
SERVER_EMAIL = env("SERVER_EMAIL", default=DEFAULT_FROM_EMAIL)

# Auth redirects
LOGIN_REDIRECT_URL = "/"
LOGOUT_REDIRECT_URL = "/"

############################
# Security Settings
############################

# SECURITY WARNING: These settings should be configured via environment variables in production!

# HTTPS Settings (only enable in production with SSL)
SECURE_SSL_REDIRECT = env.bool("SECURE_SSL_REDIRECT", default=False)
SECURE_PROXY_SSL_HEADER = env.tuple("SECURE_PROXY_SSL_HEADER", default=None)

# HSTS (HTTP Strict Transport Security)
SECURE_HSTS_SECONDS = env.int("SECURE_HSTS_SECONDS", default=0)  # Set to 31536000 (1 year) in production
SECURE_HSTS_INCLUDE_SUBDOMAINS = env.bool("SECURE_HSTS_INCLUDE_SUBDOMAINS", default=False)
SECURE_HSTS_PRELOAD = env.bool("SECURE_HSTS_PRELOAD", default=False)

# Content Security
SECURE_CONTENT_TYPE_NOSNIFF = True
SECURE_BROWSER_XSS_FILTER = True
X_FRAME_OPTIONS = "DENY"  # Changed from default to DENY for better security

# Session Security
SESSION_COOKIE_SECURE = env.bool("SESSION_COOKIE_SECURE", default=False)  # Set to True in production with HTTPS
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = "Lax"
SESSION_COOKIE_AGE = 86400  # 24 hours
SESSION_SAVE_EVERY_REQUEST = True  # Prevent session fixation
SESSION_EXPIRE_AT_BROWSER_CLOSE = True  # Session expires when browser closes

# CSRF Security
CSRF_COOKIE_SECURE = env.bool("CSRF_COOKIE_SECURE", default=False)  # Set to True in production with HTTPS
CSRF_COOKIE_HTTPONLY = True
CSRF_COOKIE_SAMESITE = "Lax"
CSRF_TRUSTED_ORIGINS = env.list("CSRF_TRUSTED_ORIGINS", default=[])

# Password Security (already configured above, but adding additional settings)
PASSWORD_HASHERS = [
    "django.contrib.auth.hashers.Argon2PasswordHasher",  # Best option if available
    "django.contrib.auth.hashers.PBKDF2PasswordHasher",
    "django.contrib.auth.hashers.PBKDF2SHA1PasswordHasher",
    "django.contrib.auth.hashers.BCryptSHA256PasswordHasher",
    "django.contrib.auth.hashers.ScryptPasswordHasher",
]

# File Upload Security
FILE_UPLOAD_MAX_MEMORY_SIZE = 5242880  # 5 MB
DATA_UPLOAD_MAX_MEMORY_SIZE = 5242880  # 5 MB
DATA_UPLOAD_MAX_NUMBER_FIELDS = 1000

# Additional Security Headers (via middleware)
SECURE_REFERRER_POLICY = "strict-origin-when-cross-origin"

# Error Pages (custom templates for production)
# These templates will be used when DEBUG=False
# Make sure to create: templates/404.html, templates/500.html, templates/403.html

############################
# Logging Configuration
############################

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {
            "format": "{levelname} {asctime} {module} {process:d} {thread:d} {message}",
            "style": "{",
        },
        "simple": {
            "format": "{levelname} {message}",
            "style": "{",
        },
    },
    "filters": {
        "require_debug_false": {
            "()": "django.utils.log.RequireDebugFalse",
        },
        "sensitive_data_filter": {
            "()": "sami.logging_filters.SensitiveDataFilter",
        },
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "verbose",
        },
        "file": {
            "class": "logging.handlers.RotatingFileHandler",
            "filename": BASE_DIR / "logs" / "django.log",
            "maxBytes": 1024 * 1024 * 10,  # 10 MB
            "backupCount": 5,
            "formatter": "verbose",
            "filters": ["sensitive_data_filter"],  # Filter sensitive data
        },
        "security_file": {
            "class": "logging.handlers.RotatingFileHandler",
            "filename": BASE_DIR / "logs" / "security.log",
            "maxBytes": 1024 * 1024 * 10,  # 10 MB
            "backupCount": 10,
            "formatter": "verbose",
            "filters": ["sensitive_data_filter"],  # Filter sensitive data
        },
        "mail_admins": {
            "level": "ERROR",
            "filters": ["require_debug_false"],
            "class": "django.utils.log.AdminEmailHandler",
        },
    },
    "root": {
        "handlers": ["console", "file"],
        "level": "INFO",
    },
    "loggers": {
        "django": {
            "handlers": ["console", "file"],
            "level": "INFO",
            "propagate": False,
        },
        "django.security": {
            "handlers": ["security_file", "mail_admins"],
            "level": "WARNING",
            "propagate": False,
        },
        "django.request": {
            "handlers": ["file", "mail_admins"],
            "level": "ERROR",
            "propagate": False,
        },
        "accounts": {
            "handlers": ["console", "file", "security_file"],
            "level": "INFO",
            "propagate": False,
        },
    },
}

# Create logs directory if it doesn't exist
LOGS_DIR = BASE_DIR / "logs"
LOGS_DIR.mkdir(exist_ok=True)

############################
# Admin Security
############################

# Admin URL customization (change in production for better security)
ADMIN_URL = env("ADMIN_URL", default="admin/")

# Admin site header and title
ADMIN_SITE_HEADER = "Sami Deutsch Administration"
ADMIN_SITE_TITLE = "Sami Deutsch Admin"
ADMIN_INDEX_TITLE = "پنل مدیریت سامی دویچ"

# Optional: IP whitelist for admin access (comma-separated list)
# Only enable in production if needed
# ADMIN_IP_WHITELIST = env.list("ADMIN_IP_WHITELIST", default=[])

# Password reset settings
PASSWORD_RESET_TIMEOUT = 86400  # 24 hours (default)
PASSWORD_RESET_EMAIL_SUBJECT = "بازیابی رمز عبور - Sami Deutsch"

# Admin email settings (برای logging و error reporting)
ADMINS = [
    (env("ADMIN_NAME", default="Admin"), env("ADMIN_EMAIL", default="admin@example.com")),
]

# File upload permissions
FILE_UPLOAD_PERMISSIONS = 0o644
FILE_UPLOAD_DIRECTORY_PERMISSIONS = 0o755
