# Generated by Django 5.2.4 on 2025-12-03 11:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SiteVisit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("path", models.CharField(max_length=512, verbose_name="آدرس صفحه")),
                ("method", models.CharField(max_length=10, verbose_name="متد درخواست")),
                (
                    "status_code",
                    models.PositiveIntegerField(default=200, verbose_name="کد وضعیت"),
                ),
                (
                    "ip_address",
                    models.CharField(
                        blank=True, max_length=45, verbose_name="آی\u200cپی"
                    ),
                ),
                (
                    "user_agent",
                    models.TextField(blank=True, verbose_name="مرورگر / دستگاه"),
                ),
                (
                    "referrer",
                    models.TextField(blank=True, verbose_name="صفحه ارجاع\u200cدهنده"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="زمان بازدید"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="site_visits",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="کاربر",
                    ),
                ),
            ],
            options={
                "verbose_name": "بازدید صفحه",
                "verbose_name_plural": "بازدیدهای سایت",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["created_at"], name="core_sitevi_created_e7672a_idx"
                    ),
                    models.Index(fields=["path"], name="core_sitevi_path_1067d4_idx"),
                ],
            },
        ),
    ]
