# Generated by Django 5.2.4 on 2025-12-03 11:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_sitevisit"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="YouTubeClick",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("youtube_url", models.URLField(verbose_name="لینک یوتیوب")),
                (
                    "youtube_id",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="شناسه ویدیو یوتیوب"
                    ),
                ),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("video", "ویدیو"),
                            ("post", "مقاله"),
                            ("other", "سایر"),
                        ],
                        default="other",
                        max_length=10,
                        verbose_name="نوع منبع",
                    ),
                ),
                (
                    "source_id",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="شناسه منبع"
                    ),
                ),
                (
                    "source_title",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="عنوان منبع"
                    ),
                ),
                (
                    "ip_address",
                    models.CharField(
                        blank=True, max_length=45, verbose_name="آی\u200cپی"
                    ),
                ),
                (
                    "user_agent",
                    models.TextField(blank=True, verbose_name="مرورگر / دستگاه"),
                ),
                (
                    "referrer",
                    models.TextField(blank=True, verbose_name="صفحه ارجاع\u200cدهنده"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="زمان کلیک"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="youtube_clicks",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="کاربر",
                    ),
                ),
            ],
            options={
                "verbose_name": "کلیک یوتیوب",
                "verbose_name_plural": "کلیک\u200cهای یوتیوب",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["created_at"], name="core_youtub_created_0fbdad_idx"
                    ),
                    models.Index(
                        fields=["youtube_id"], name="core_youtub_youtube_e26291_idx"
                    ),
                    models.Index(
                        fields=["source_type", "source_id"],
                        name="core_youtub_source__f83da4_idx",
                    ),
                ],
            },
        ),
    ]
