# Generated by Django 5.2.4 on 2025-12-03 12:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_youtubeclick"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AnonymousVisitor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "session_key",
                    models.CharField(
                        db_index=True,
                        help_text="شناسه منحصر به فرد نشست Django",
                        max_length=40,
                        unique=True,
                        verbose_name="کلید نشست",
                    ),
                ),
                (
                    "first_seen",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="اولین بازدید"
                    ),
                ),
                (
                    "last_seen",
                    models.DateTimeField(auto_now=True, verbose_name="آخرین بازدید"),
                ),
                (
                    "first_ip",
                    models.CharField(
                        blank=True, max_length=45, verbose_name="اولین آی\u200cپی"
                    ),
                ),
                (
                    "last_ip",
                    models.CharField(
                        blank=True, max_length=45, verbose_name="آخرین آی\u200cپی"
                    ),
                ),
                (
                    "first_user_agent",
                    models.TextField(blank=True, verbose_name="اولین مرورگر / دستگاه"),
                ),
                (
                    "last_user_agent",
                    models.TextField(blank=True, verbose_name="آخرین مرورگر / دستگاه"),
                ),
            ],
            options={
                "verbose_name": "بازدیدکننده ناشناس",
                "verbose_name_plural": "بازدیدکنندگان ناشناس",
                "ordering": ["-last_seen"],
                "indexes": [
                    models.Index(
                        fields=["session_key"], name="core_anonym_session_b1526c_idx"
                    ),
                    models.Index(
                        fields=["last_seen"], name="core_anonym_last_se_b75dcc_idx"
                    ),
                ],
            },
        ),
        migrations.AddField(
            model_name="sitevisit",
            name="anonymous_visitor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="site_visits",
                to="core.anonymousvisitor",
                verbose_name="بازدیدکننده ناشناس",
            ),
        ),
        migrations.AddField(
            model_name="youtubeclick",
            name="anonymous_visitor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="youtube_clicks",
                to="core.anonymousvisitor",
                verbose_name="بازدیدکننده ناشناس",
            ),
        ),
        migrations.AddIndex(
            model_name="sitevisit",
            index=models.Index(
                fields=["anonymous_visitor"], name="core_sitevi_anonymo_ab6d31_idx"
            ),
        ),
    ]
