# Generated by Django 5.2.4 on 2025-12-03 12:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_anonymousvisitor_sitevisit_anonymous_visitor_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="anonymousvisitor",
            name="first_country",
            field=models.CharField(blank=True, max_length=2, verbose_name="اولین کشور"),
        ),
        migrations.AddField(
            model_name="anonymousvisitor",
            name="last_country",
            field=models.CharField(blank=True, max_length=2, verbose_name="آخرین کشور"),
        ),
        migrations.AddField(
            model_name="sitevisit",
            name="country",
            field=models.CharField(blank=True, max_length=2, verbose_name="کشور"),
        ),
        migrations.AddField(
            model_name="youtubeclick",
            name="country",
            field=models.CharField(blank=True, max_length=2, verbose_name="کشور"),
        ),
        migrations.AddIndex(
            model_name="sitevisit",
            index=models.Index(
                fields=["country"], name="core_sitevi_country_8ae93f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="youtubeclick",
            index=models.Index(
                fields=["country"], name="core_youtub_country_e6028b_idx"
            ),
        ),
    ]
