# Generated by Django 5.2.4 on 2025-12-03 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_anonymousvisitor_first_country_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitevisit",
            name="device_type",
            field=models.CharField(
                blank=True, max_length=20, verbose_name="نوع دستگاه"
            ),
        ),
    ]
