# Generated by Django 5.2.4 on 2025-12-03 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="user_category",
            field=models.CharField(
                choices=[("user", "یوزر معمولی"), ("admin", "مدیر سایت")],
                default="user",
                help_text="دسته\u200cبندی کاربر برای تعیین سطح دسترسی",
                max_length=10,
                verbose_name="دسته\u200cبندی کاربر",
            ),
        ),
    ]
