# Generated by Django 5.2.4 on 2025-08-18 09:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="نام")),
                (
                    "slug",
                    models.SlugField(
                        allow_unicode=True,
                        max_length=120,
                        unique=True,
                        verbose_name="اسلاگ",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="توضیحات"),
                ),
                (
                    "color",
                    models.CharField(
                        default="#007bff", max_length=7, verbose_name="رنگ"
                    ),
                ),
            ],
            options={
                "verbose_name": "دسته\u200cبندی",
                "verbose_name_plural": "دسته\u200cبندی\u200cها",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(default="", max_length=250, verbose_name="عنوان"),
                ),
                (
                    "slug",
                    models.SlugField(
                        allow_unicode=True, default="", max_length=270, unique=True
                    ),
                ),
                ("content", models.TextField(default="", verbose_name="محتوا")),
                (
                    "excerpt",
                    models.TextField(
                        blank=True, max_length=500, null=True, verbose_name="خلاصه"
                    ),
                ),
                (
                    "cover",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="blog/covers/",
                        verbose_name="عکس کاور",
                    ),
                ),
                (
                    "youtube_video_id",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        verbose_name="شناسه ویدیو یوتیوب",
                    ),
                ),
                (
                    "is_featured",
                    models.BooleanField(default=False, verbose_name="ویژه"),
                ),
                (
                    "published_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاریخ انتشار"
                    ),
                ),
                (
                    "views_count",
                    models.PositiveIntegerField(default=0, verbose_name="تعداد بازدید"),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="blog.category",
                        verbose_name="دسته\u200cبندی",
                    ),
                ),
            ],
            options={
                "verbose_name": "مقاله",
                "verbose_name_plural": "مقالات",
                "ordering": ["-published_at"],
            },
        ),
    ]
