# Generated by Django 5.2.4 on 2025-08-15 13:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="نام")),
                (
                    "slug",
                    models.SlugField(
                        allow_unicode=True,
                        max_length=120,
                        unique=True,
                        verbose_name="اسلاگ",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="توضیحات"),
                ),
                (
                    "color",
                    models.CharField(
                        default="#007bff", max_length=7, verbose_name="رنگ"
                    ),
                ),
            ],
            options={
                "verbose_name": "دسته\u200cبندی",
                "verbose_name_plural": "دسته\u200cبندی\u200cها",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="post",
            name="is_featured",
            field=models.BooleanField(default=False, verbose_name="ویژه"),
        ),
        migrations.AddField(
            model_name="post",
            name="views_count",
            field=models.PositiveIntegerField(default=0, verbose_name="تعداد بازدید"),
        ),
        migrations.AddField(
            model_name="post",
            name="youtube_video_id",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="شناسه ویدیو یوتیوب"
            ),
        ),
        migrations.AddField(
            model_name="posttranslation",
            name="excerpt",
            field=models.TextField(
                blank=True, max_length=500, null=True, verbose_name="خلاصه"
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="cover",
            field=models.ImageField(
                blank=True, null=True, upload_to="blog/covers/", verbose_name="عکس کاور"
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="published_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="تاریخ انتشار"),
        ),
        migrations.AddField(
            model_name="post",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="blog.category",
                verbose_name="دسته\u200cبندی",
            ),
        ),
    ]
