# Generated by Django 5.2.4 on 2025-08-18 09:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Video",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(default="", max_length=200, verbose_name="عنوان"),
                ),
                (
                    "description",
                    models.TextField(blank=True, default="", verbose_name="توضیحات"),
                ),
                (
                    "slug",
                    models.SlugField(
                        allow_unicode=True, default="", max_length=220, unique=True
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("A1", "A1"),
                            ("A2", "A2"),
                            ("B1", "B1"),
                            ("B2", "B2"),
                            ("C1", "C1"),
                        ],
                        max_length=2,
                        verbose_name="سطح",
                    ),
                ),
                (
                    "topic",
                    models.CharField(
                        choices=[
                            ("grammar", "گرامر"),
                            ("speaking", "مکالمه"),
                            ("vocab", "واژگان"),
                            ("listening", "شنیداری"),
                            ("reading", "خواندن"),
                            ("writing", "نوشتن"),
                            ("culture", "فرهنگ"),
                            ("pronunciation", "تلفظ"),
                        ],
                        max_length=50,
                        verbose_name="موضوع",
                    ),
                ),
                (
                    "cover",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="videos/covers/",
                        verbose_name="تصویر کاور",
                    ),
                ),
                (
                    "duration_minutes",
                    models.PositiveIntegerField(
                        default=0, verbose_name="مدت زمان (دقیقه)"
                    ),
                ),
                (
                    "difficulty",
                    models.CharField(
                        choices=[
                            ("beginner", "مبتدی"),
                            ("intermediate", "متوسط"),
                            ("advanced", "پیشرفته"),
                        ],
                        default="beginner",
                        max_length=20,
                        verbose_name="سطح دشواری",
                    ),
                ),
                (
                    "is_featured",
                    models.BooleanField(default=False, verbose_name="ویژه"),
                ),
                ("is_free", models.BooleanField(default=True, verbose_name="رایگان")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "ویدیو",
                "verbose_name_plural": "ویدیوها",
                "ordering": ["-is_featured", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="VideoImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(upload_to="videos/images/", verbose_name="تصویر"),
                ),
                (
                    "caption",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="توضیح تصویر"
                    ),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(default=0, verbose_name="ترتیب"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="فعال")),
                (
                    "video",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="courses.video",
                        verbose_name="ویدیو",
                    ),
                ),
            ],
            options={
                "verbose_name": "تصویر ویدیو",
                "verbose_name_plural": "تصاویر ویدیو",
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="VideoTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=50, unique=True, verbose_name="نام تگ"),
                ),
                (
                    "color",
                    models.CharField(
                        default="#0d6efd", max_length=7, verbose_name="رنگ تگ"
                    ),
                ),
                (
                    "videos",
                    models.ManyToManyField(
                        blank=True,
                        related_name="tags",
                        to="courses.video",
                        verbose_name="ویدیوها",
                    ),
                ),
            ],
            options={
                "verbose_name": "تگ ویدیو",
                "verbose_name_plural": "تگ\u200cهای ویدیو",
            },
        ),
        migrations.CreateModel(
            name="YouTubeLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="عنوان")),
                ("youtube_url", models.URLField(verbose_name="لینک یوتیوب")),
                ("description", models.TextField(blank=True, verbose_name="توضیحات")),
                (
                    "duration_minutes",
                    models.PositiveIntegerField(
                        default=0, verbose_name="مدت زمان (دقیقه)"
                    ),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(default=0, verbose_name="ترتیب"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="فعال")),
                (
                    "video",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="youtube_links",
                        to="courses.video",
                        verbose_name="ویدیو",
                    ),
                ),
            ],
            options={
                "verbose_name": "لینک یوتیوب",
                "verbose_name_plural": "لینک\u200cهای یوتیوب",
                "ordering": ["order", "id"],
            },
        ),
    ]
