# Generated by Django 5.1.11 on 2025-08-11 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FooterLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50)),
                ("url", models.CharField(max_length=200)),
                ("order", models.PositiveSmallIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "لینک فوتر",
                "verbose_name_plural": "لینک\u200cهای فوتر",
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="HomeFeature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=60)),
                ("subtitle", models.CharField(blank=True, default="", max_length=120)),
                (
                    "icon",
                    models.CharField(
                        blank=True, default="fa-solid fa-star", max_length=50
                    ),
                ),
                ("order", models.PositiveSmallIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "ویژگی صفحه اصلی",
                "verbose_name_plural": "ویژگی\u200cهای صفحه اصلی",
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="NavLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50)),
                ("url", models.CharField(max_length=200)),
                ("order", models.PositiveSmallIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "لینک ناوبری",
                "verbose_name_plural": "لینک\u200cهای ناوبری",
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="SiteSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("brand_name", models.CharField(default="Sami", max_length=50)),
                (
                    "logo",
                    models.ImageField(blank=True, null=True, upload_to="branding/"),
                ),
                ("primary_color", models.CharField(default="#0d6efd", max_length=7)),
                (
                    "meta_description",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                ("footer_text", models.TextField(blank=True, default="")),
                (
                    "hero_title",
                    models.CharField(
                        blank=True, default="آموزش آلمانی، سریع و اصولی", max_length=120
                    ),
                ),
                (
                    "hero_subtitle",
                    models.CharField(
                        blank=True,
                        default="دوره\u200cهای سطح\u200cبندی شده، تمرین\u200cهای تعاملی و آزمون تعیین سطح هوشمند",
                        max_length=200,
                    ),
                ),
                (
                    "hero_video_url",
                    models.URLField(
                        blank=True, default="https://www.youtube.com/embed/hHW1oY26kxQ"
                    ),
                ),
                ("show_newsletter", models.BooleanField(default=True)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
