# Generated by Django 5.1.11 on 2025-08-11 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("siteconfig", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="HomeSlider",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("autoplay", models.BooleanField(default=True)),
                ("interval_ms", models.PositiveIntegerField(default=5000)),
                ("show_arrows", models.BooleanField(default=True)),
                ("show_indicators", models.BooleanField(default=True)),
                ("pause_on_hover", models.BooleanField(default=True)),
                (
                    "aspect_ratio",
                    models.CharField(
                        default="21x9", help_text="مثل 16x9 یا 21x9", max_length=10
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Slide",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=120)),
                ("subtitle", models.CharField(blank=True, default="", max_length=200)),
                ("image", models.ImageField(upload_to="slides/")),
                ("cta_text", models.CharField(blank=True, default="", max_length=50)),
                ("cta_url", models.CharField(blank=True, default="", max_length=200)),
                (
                    "text_align",
                    models.CharField(
                        choices=[
                            ("start", "Start"),
                            ("center", "Center"),
                            ("end", "End"),
                        ],
                        default="start",
                        max_length=10,
                    ),
                ),
                ("order", models.PositiveSmallIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "اسلاید",
                "verbose_name_plural": "اسلایدها",
                "ordering": ["order", "id"],
            },
        ),
    ]
