# Generated by Django 5.1.11 on 2025-08-11 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("siteconfig", "0002_homeslider_slide"),
    ]

    operations = [
        migrations.AddField(
            model_name="slide",
            name="button_bg_color",
            field=models.CharField(default="#0d6efd", max_length=7),
        ),
        migrations.AddField(
            model_name="slide",
            name="button_text_color",
            field=models.CharField(default="#ffffff", max_length=7),
        ),
        migrations.AddField(
            model_name="slide",
            name="caption_bg_color",
            field=models.CharField(default="#000000", max_length=7),
        ),
        migrations.AddField(
            model_name="slide",
            name="caption_bg_opacity",
            field=models.PositiveSmallIntegerField(default=40, help_text="0-100 درصد"),
        ),
        migrations.AddField(
            model_name="slide",
            name="overlay_h_align",
            field=models.CharField(
                choices=[("start", "Start"), ("center", "Center"), ("end", "End")],
                default="center",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="slide",
            name="overlay_v_align",
            field=models.CharField(
                choices=[("top", "Top"), ("center", "Center"), ("bottom", "Bottom")],
                default="bottom",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="slide",
            name="text_color",
            field=models.CharField(default="#ffffff", max_length=7),
        ),
    ]
