# Generated by Django 5.1.11 on 2025-08-11 15:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("siteconfig", "0003_slide_button_bg_color_slide_button_text_color_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Menu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("slug", models.SlugField(unique=True)),
                (
                    "location",
                    models.CharField(
                        choices=[("header", "هدر"), ("footer", "فوتر")],
                        default="header",
                        max_length=10,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MenuItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=80)),
                ("url", models.CharField(max_length=300)),
                ("icon_class", models.CharField(blank=True, default="", max_length=50)),
                ("order", models.PositiveSmallIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "menu",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="siteconfig.menu",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="siteconfig.menuitem",
                    ),
                ),
            ],
            options={
                "verbose_name": "آیتم منو",
                "verbose_name_plural": "آیتم\u200cهای منو",
                "ordering": ["order", "id"],
            },
        ),
    ]
