# Generated by Django 5.1.11 on 2025-08-11 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("siteconfig", "0004_menu_menuitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="show_default_nav_links",
            field=models.BooleanField(default=True),
        ),
    ]
