# Generated by Django 5.2.4 on 2025-08-15 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("siteconfig", "0005_sitesettings_show_default_nav_links"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="base_font_size",
            field=models.CharField(
                default="16px", max_length=10, verbose_name="اندازه فونت پایه"
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="body_bg_color",
            field=models.CharField(
                default="#ffffff", max_length=7, verbose_name="رنگ پس\u200cزمینه صفحه"
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="body_font_family",
            field=models.CharField(
                default="Vazirmatn", max_length=100, verbose_name="فونت متن"
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="button_outline_color",
            field=models.CharField(
                default="#0d6efd", max_length=7, verbose_name="رنگ حاشیه دکمه outline"
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="button_primary_bg",
            field=models.CharField(
                default="#0d6efd",
                max_length=7,
                verbose_name="رنگ پس\u200cزمینه دکمه اصلی",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="button_primary_text",
            field=models.CharField(
                default="#ffffff", max_length=7, verbose_name="رنگ متن دکمه اصلی"
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="button_secondary_bg",
            field=models.CharField(
                default="#6c757d",
                max_length=7,
                verbose_name="رنگ پس\u200cزمینه دکمه ثانویه",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="button_secondary_text",
            field=models.CharField(
                default="#ffffff", max_length=7, verbose_name="رنگ متن دکمه ثانویه"
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="card_bg_color",
            field=models.CharField(
                default="#ffffff",
                max_length=7,
                verbose_name="رنگ پس\u200cزمینه کارت\u200cها",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="card_border_color",
            field=models.CharField(
                default="#dee2e6", max_length=7, verbose_name="رنگ حاشیه کارت\u200cها"
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="card_border_radius",
            field=models.CharField(
                default="0.375rem", max_length=20, verbose_name="گردی گوشه کارت\u200cها"
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="card_shadow_color",
            field=models.CharField(
                default="rgba(0,0,0,0.1)",
                max_length=7,
                verbose_name="رنگ سایه کارت\u200cها",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="container_max_width",
            field=models.CharField(
                default="1200px", max_length=20, verbose_name="حداکثر عرض کانتینر"
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="custom_css",
            field=models.TextField(
                blank=True,
                help_text="کدهای CSS اضافی برای شخصی\u200cسازی بیشتر",
                verbose_name="CSS سفارشی",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="error_color",
            field=models.CharField(
                default="#dc3545", max_length=7, verbose_name="رنگ خطا"
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="footer_bg_color",
            field=models.CharField(
                default="#212529", max_length=7, verbose_name="رنگ پس\u200cزمینه فوتر"
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="footer_text_color",
            field=models.CharField(
                default="#ffffff", max_length=7, verbose_name="رنگ متن فوتر"
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="heading_font_family",
            field=models.CharField(
                default="Vazirmatn", max_length=100, verbose_name="فونت عناوین"
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="info_color",
            field=models.CharField(
                default="#0dcaf0", max_length=7, verbose_name="رنگ اطلاعات"
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="link_color",
            field=models.CharField(
                default="#0d6efd", max_length=7, verbose_name="رنگ لینک\u200cها"
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="link_hover_color",
            field=models.CharField(
                default="#0a58ca", max_length=7, verbose_name="رنگ هاور لینک\u200cها"
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="navbar_bg_color",
            field=models.CharField(
                default="#0d6efd", max_length=7, verbose_name="رنگ پس\u200cزمینه منو"
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="navbar_hover_color",
            field=models.CharField(
                default="#0b5ed7", max_length=7, verbose_name="رنگ هاور منو"
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="navbar_text_color",
            field=models.CharField(
                default="#ffffff", max_length=7, verbose_name="رنگ متن منو"
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="section_bg_color",
            field=models.CharField(
                default="#f8f9fa",
                max_length=7,
                verbose_name="رنگ پس\u200cزمینه بخش\u200cها",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="section_padding",
            field=models.CharField(
                default="4rem", max_length=20, verbose_name="فاصله بخش\u200cها"
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="success_color",
            field=models.CharField(
                default="#198754", max_length=7, verbose_name="رنگ موفقیت"
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="text_muted_color",
            field=models.CharField(
                default="#adb5bd", max_length=7, verbose_name="رنگ متن کمرنگ"
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="text_primary_color",
            field=models.CharField(
                default="#0f172a", max_length=7, verbose_name="رنگ متن اصلی"
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="text_secondary_color",
            field=models.CharField(
                default="#6c757d", max_length=7, verbose_name="رنگ متن ثانویه"
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="warning_color",
            field=models.CharField(
                default="#ffc107", max_length=7, verbose_name="رنگ هشدار"
            ),
        ),
    ]
