# Generated by Django 5.2.4 on 2025-08-17 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("siteconfig", "0006_sitesettings_base_font_size_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="hero_bg_color",
            field=models.CharField(
                blank=True,
                default="#f8f9fa",
                max_length=7,
                verbose_name="رنگ پس\u200cزمینه هیرو",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="hero_description",
            field=models.TextField(
                blank=True,
                default="با بهترین روش\u200cهای آموزشی، زبان آلمانی را به صورت خودخوان و کاربردی یاد بگیرید. از سطح A1 تا C1، با ویدیوهای آموزشی، مقالات تخصصی و آزمون\u200cهای استاندارد.",
                verbose_name="توضیحات هیرو",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="hero_description_color",
            field=models.CharField(
                blank=True, default="#6c757d", max_length=7, verbose_name="رنگ توضیحات"
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="hero_floating_element_1_color",
            field=models.CharField(
                blank=True,
                default="#198754",
                max_length=7,
                verbose_name="رنگ عنصر شناور 1",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="hero_floating_element_1_icon",
            field=models.CharField(
                blank=True,
                default="fas fa-video",
                max_length=50,
                verbose_name="آیکون عنصر شناور 1",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="hero_floating_element_1_title",
            field=models.CharField(
                blank=True,
                default="ویدیوهای آموزشی",
                max_length=50,
                verbose_name="عنوان عنصر شناور 1",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="hero_floating_element_2_color",
            field=models.CharField(
                blank=True,
                default="#0dcaf0",
                max_length=7,
                verbose_name="رنگ عنصر شناور 2",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="hero_floating_element_2_icon",
            field=models.CharField(
                blank=True,
                default="fas fa-book",
                max_length=50,
                verbose_name="آیکون عنصر شناور 2",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="hero_floating_element_2_title",
            field=models.CharField(
                blank=True,
                default="مقالات تخصصی",
                max_length=50,
                verbose_name="عنوان عنصر شناور 2",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="hero_floating_element_3_color",
            field=models.CharField(
                blank=True,
                default="#ffc107",
                max_length=7,
                verbose_name="رنگ عنصر شناور 3",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="hero_floating_element_3_icon",
            field=models.CharField(
                blank=True,
                default="fas fa-trophy",
                max_length=50,
                verbose_name="آیکون عنصر شناور 3",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="hero_floating_element_3_title",
            field=models.CharField(
                blank=True,
                default="آزمون\u200cهای استاندارد",
                max_length=50,
                verbose_name="عنوان عنصر شناور 3",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="hero_icon",
            field=models.CharField(
                blank=True,
                default="fas fa-graduation-cap",
                max_length=50,
                verbose_name="آیکون هیرو",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="hero_icon_color",
            field=models.CharField(
                blank=True, default="#0d6efd", max_length=7, verbose_name="رنگ آیکون"
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="hero_icon_size",
            field=models.CharField(
                blank=True, default="fa-8x", max_length=20, verbose_name="اندازه آیکون"
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="hero_image",
            field=models.ImageField(
                blank=True, null=True, upload_to="hero/", verbose_name="تصویر هیرو"
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="hero_primary_button_text",
            field=models.CharField(
                blank=True,
                default="شروع یادگیری",
                max_length=50,
                verbose_name="متن دکمه اصلی",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="hero_primary_button_url",
            field=models.CharField(
                blank=True,
                default="/videos/",
                max_length=200,
                verbose_name="لینک دکمه اصلی",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="hero_secondary_button_text",
            field=models.CharField(
                blank=True,
                default="تعیین سطح",
                max_length=50,
                verbose_name="متن دکمه ثانویه",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="hero_secondary_button_url",
            field=models.CharField(
                blank=True,
                default="/assessments/",
                max_length=200,
                verbose_name="لینک دکمه ثانویه",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="hero_stats_posts_color",
            field=models.CharField(
                blank=True,
                default="#198754",
                max_length=7,
                verbose_name="رنگ آمار مقالات",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="hero_stats_posts_count",
            field=models.PositiveIntegerField(default=50, verbose_name="تعداد مقالات"),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="hero_stats_posts_icon",
            field=models.CharField(
                blank=True,
                default="fas fa-newspaper",
                max_length=50,
                verbose_name="آیکون مقالات",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="hero_stats_posts_title",
            field=models.CharField(
                blank=True,
                default="مقاله تخصصی",
                max_length=50,
                verbose_name="عنوان آمار مقالات",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="hero_stats_products_color",
            field=models.CharField(
                blank=True,
                default="#ffc107",
                max_length=7,
                verbose_name="رنگ آمار محصولات",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="hero_stats_products_count",
            field=models.PositiveIntegerField(default=25, verbose_name="تعداد محصولات"),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="hero_stats_products_icon",
            field=models.CharField(
                blank=True,
                default="fas fa-shopping-bag",
                max_length=50,
                verbose_name="آیکون محصولات",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="hero_stats_products_title",
            field=models.CharField(
                blank=True,
                default="پکیج آموزشی",
                max_length=50,
                verbose_name="عنوان آمار محصولات",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="hero_stats_students_color",
            field=models.CharField(
                blank=True,
                default="#0dcaf0",
                max_length=7,
                verbose_name="رنگ آمار دانشجویان",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="hero_stats_students_count",
            field=models.PositiveIntegerField(
                default=1000, verbose_name="تعداد دانشجویان"
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="hero_stats_students_icon",
            field=models.CharField(
                blank=True,
                default="fas fa-users",
                max_length=50,
                verbose_name="آیکون دانشجویان",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="hero_stats_students_title",
            field=models.CharField(
                blank=True,
                default="دانشجو",
                max_length=50,
                verbose_name="عنوان آمار دانشجویان",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="hero_stats_videos_color",
            field=models.CharField(
                blank=True,
                default="#0d6efd",
                max_length=7,
                verbose_name="رنگ آمار ویدیوها",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="hero_stats_videos_count",
            field=models.PositiveIntegerField(
                default=100, verbose_name="تعداد ویدیوها"
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="hero_stats_videos_icon",
            field=models.CharField(
                blank=True,
                default="fas fa-video",
                max_length=50,
                verbose_name="آیکون ویدیوها",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="hero_stats_videos_title",
            field=models.CharField(
                blank=True,
                default="ویدیوی آموزشی",
                max_length=50,
                verbose_name="عنوان آمار ویدیوها",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="hero_subtitle_color",
            field=models.CharField(
                blank=True, default="#6c757d", max_length=7, verbose_name="رنگ زیرعنوان"
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="hero_text_color",
            field=models.CharField(
                blank=True, default="#0f172a", max_length=7, verbose_name="رنگ متن هیرو"
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="show_hero_floating_elements",
            field=models.BooleanField(default=True, verbose_name="نمایش عناصر شناور"),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="show_hero_newsletter",
            field=models.BooleanField(default=True, verbose_name="نمایش خبرنامه"),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="show_hero_stats",
            field=models.BooleanField(default=True, verbose_name="نمایش آمار"),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="show_hero_video",
            field=models.BooleanField(default=False, verbose_name="نمایش ویدیو هیرو"),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="hero_subtitle",
            field=models.CharField(
                blank=True,
                default="از پایه تا پیشرفته",
                max_length=200,
                verbose_name="زیرعنوان هیرو",
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="hero_title",
            field=models.CharField(
                blank=True,
                default="آموزش زبان آلمانی",
                max_length=120,
                verbose_name="عنوان اصلی هیرو",
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="hero_video_url",
            field=models.URLField(
                blank=True,
                default="https://www.youtube.com/embed/hHW1oY26kxQ",
                verbose_name="لینک ویدیو هیرو",
            ),
        ),
    ]
