# Generated by Django 5.2.4 on 2025-12-02 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("siteconfig", "0007_sitesettings_hero_bg_color_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="HomePageSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "section_type",
                    models.CharField(
                        choices=[
                            ("videos", "ویدیوها"),
                            ("products", "محصولات"),
                            ("posts", "مقالات"),
                        ],
                        help_text="نوع محتوایی که در این بخش نمایش داده می\u200cشود",
                        max_length=20,
                        verbose_name="نوع بخش",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="مثلاً: ویدیوهای جدید، پکیج\u200cهای آموزشی",
                        max_length=100,
                        verbose_name="عنوان بخش",
                    ),
                ),
                (
                    "subtitle",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="توضیح کوتاه برای بخش",
                        max_length=200,
                        verbose_name="زیرعنوان",
                    ),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(
                        default=0,
                        help_text="بخش\u200cها بر اساس این عدد مرتب می\u200cشوند",
                        verbose_name="ترتیب نمایش",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="اگر غیرفعال باشد، این بخش نمایش داده نمی\u200cشود",
                        verbose_name="فعال",
                    ),
                ),
                (
                    "item_count",
                    models.PositiveSmallIntegerField(
                        default=6,
                        help_text="تعداد آیتم\u200cهایی که در این بخش نمایش داده می\u200cشود",
                        verbose_name="تعداد آیتم\u200cها",
                    ),
                ),
                (
                    "video_filter_featured",
                    models.BooleanField(
                        default=False,
                        help_text="اگر فعال باشد، فقط ویدیوهای ویژه نمایش داده می\u200cشوند",
                        verbose_name="فقط ویدیوهای ویژه",
                    ),
                ),
                (
                    "video_filter_level",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("A1", "A1"),
                            ("A2", "A2"),
                            ("B1", "B1"),
                            ("B2", "B2"),
                            ("C1", "C1"),
                        ],
                        help_text="اگر انتخاب شود، فقط ویدیوهای این سطح نمایش داده می\u200cشوند",
                        max_length=10,
                        null=True,
                        verbose_name="فیلتر بر اساس سطح",
                    ),
                ),
                (
                    "video_filter_topic",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("grammar", "گرامر"),
                            ("speaking", "مکالمه"),
                            ("vocab", "واژگان"),
                            ("listening", "شنیداری"),
                            ("reading", "خواندن"),
                            ("writing", "نوشتن"),
                            ("culture", "فرهنگ"),
                            ("pronunciation", "تلفظ"),
                        ],
                        help_text="اگر انتخاب شود، فقط ویدیوهای این موضوع نمایش داده می\u200cشوند",
                        max_length=50,
                        null=True,
                        verbose_name="فیلتر بر اساس موضوع",
                    ),
                ),
                (
                    "product_filter_featured",
                    models.BooleanField(
                        default=False,
                        help_text="اگر فعال باشد، فقط محصولات ویژه نمایش داده می\u200cشوند",
                        verbose_name="فقط محصولات ویژه",
                    ),
                ),
                (
                    "product_filter_active",
                    models.BooleanField(
                        default=True,
                        help_text="فقط محصولات فعال نمایش داده می\u200cشوند",
                        verbose_name="فقط محصولات فعال",
                    ),
                ),
                (
                    "post_filter_featured",
                    models.BooleanField(
                        default=False,
                        help_text="اگر فعال باشد، فقط مقالات ویژه نمایش داده می\u200cشوند",
                        verbose_name="فقط مقالات ویژه",
                    ),
                ),
                (
                    "show_view_all_button",
                    models.BooleanField(
                        default=True,
                        help_text="اگر فعال باشد، دکمه 'همه' نمایش داده می\u200cشود",
                        verbose_name="نمایش دکمه 'همه'",
                    ),
                ),
                (
                    "view_all_button_text",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="مثلاً: همه ویدیوها، همه پکیج\u200cها. اگر خالی باشد، به صورت خودکار تنظیم می\u200cشود",
                        max_length=50,
                        verbose_name="متن دکمه 'همه'",
                    ),
                ),
                (
                    "view_all_button_url",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="مثلاً: /videos/، /shop/. اگر خالی باشد، به صورت خودکار تنظیم می\u200cشود",
                        max_length=200,
                        verbose_name="لینک دکمه 'همه'",
                    ),
                ),
                (
                    "view_all_button_icon",
                    models.CharField(
                        blank=True,
                        default="fas fa-arrow-left",
                        max_length=50,
                        verbose_name="آیکون دکمه 'همه'",
                    ),
                ),
                (
                    "section_icon",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="آیکون FontAwesome برای بخش (اختیاری)",
                        max_length=50,
                        verbose_name="آیکون بخش",
                    ),
                ),
            ],
            options={
                "verbose_name": "بخش صفحه هوم",
                "verbose_name_plural": "بخش\u200cهای صفحه هوم",
                "ordering": ["order", "id"],
            },
        ),
    ]
