# Generated by Django 5.2.4 on 2025-12-02 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("siteconfig", "0008_homepagesection"),
    ]

    operations = [
        migrations.AddField(
            model_name="homepagesection",
            name="video_filter_difficulty",
            field=models.CharField(
                blank=True,
                choices=[
                    ("beginner", "مبتدی"),
                    ("intermediate", "متوسط"),
                    ("advanced", "پیشرفته"),
                ],
                help_text="اگر انتخاب شود، فقط ویدیوهای این سطح دشواری نمایش داده می\u200cشوند",
                max_length=20,
                null=True,
                verbose_name="فیلتر بر اساس سطح دشواری",
            ),
        ),
        migrations.AddField(
            model_name="homepagesection",
            name="video_filter_duration_max",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="فقط ویدیوهایی که حداکثر این مدت زمان را دارند نمایش داده می\u200cشوند",
                null=True,
                verbose_name="حداکثر مدت زمان (دقیقه)",
            ),
        ),
        migrations.AddField(
            model_name="homepagesection",
            name="video_filter_duration_min",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="فقط ویدیوهایی که حداقل این مدت زمان را دارند نمایش داده می\u200cشوند",
                null=True,
                verbose_name="حداقل مدت زمان (دقیقه)",
            ),
        ),
        migrations.AddField(
            model_name="homepagesection",
            name="video_filter_has_youtube",
            field=models.BooleanField(
                default=False,
                help_text="اگر فعال باشد، فقط ویدیوهایی که لینک یوتیوب دارند نمایش داده می\u200cشوند",
                verbose_name="فقط ویدیوهای دارای لینک یوتیوب",
            ),
        ),
        migrations.AddField(
            model_name="homepagesection",
            name="video_filter_is_free",
            field=models.BooleanField(
                default=False,
                help_text="اگر فعال باشد، فقط ویدیوهای رایگان نمایش داده می\u200cشوند",
                verbose_name="فقط ویدیوهای رایگان",
            ),
        ),
        migrations.AddField(
            model_name="homepagesection",
            name="video_order_by",
            field=models.CharField(
                blank=True,
                choices=[
                    ("-created_at", "جدیدترین (پیش\u200cفرض)"),
                    ("created_at", "قدیمی\u200cترین"),
                    ("-duration_minutes", "طولانی\u200cترین"),
                    ("duration_minutes", "کوتاه\u200cترین"),
                    ("title", "عنوان (الفبایی)"),
                    ("-title", "عنوان (الفبایی معکوس)"),
                    ("-is_featured", "ویژه اول"),
                ],
                default="-created_at",
                help_text="نحوه مرتب\u200cسازی ویدیوها در این بخش",
                max_length=30,
                verbose_name="مرتب\u200cسازی بر اساس",
            ),
        ),
    ]
