# Generated by Django 5.2.4 on 2025-12-02 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0001_initial"),
        ("siteconfig", "0009_homepagesection_video_filter_difficulty_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="homepagesection",
            name="manual_videos",
            field=models.ManyToManyField(
                blank=True,
                help_text="اگر این فیلد خالی نباشد و 'انتخاب دستی' فعال باشد، فقط همین ویدیوها نمایش داده می\u200cشوند",
                related_name="home_manual_sections",
                to="courses.video",
                verbose_name="ویدیوهای انتخاب\u200cشده دستی",
            ),
        ),
        migrations.AddField(
            model_name="homepagesection",
            name="use_manual_items",
            field=models.BooleanField(
                default=False,
                help_text="اگر فعال باشد، به\u200cجای فیلتر، آیتم\u200cها را به\u200cصورت دستی انتخاب می\u200cکنید",
                verbose_name="انتخاب دستی آیتم\u200cها",
            ),
        ),
        migrations.AlterField(
            model_name="homepagesection",
            name="section_type",
            field=models.CharField(
                choices=[
                    ("videos", "ویدیوها"),
                    ("products", "محصولات"),
                    ("posts", "مقالات"),
                    ("slider", "اسلایدر"),
                ],
                help_text="نوع محتوایی که در این بخش نمایش داده می\u200cشود",
                max_length=20,
                verbose_name="نوع بخش",
            ),
        ),
    ]
