# Generated by Django 5.2.4 on 2025-12-02 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("siteconfig", "0010_homepagesection_manual_videos_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="homeslider",
            name="custom_order",
            field=models.PositiveSmallIntegerField(
                default=0,
                help_text="فقط وقتی موقعیت 'سفارشی' انتخاب شده باشد استفاده می\u200cشود",
                verbose_name="ترتیب سفارشی",
            ),
        ),
        migrations.AddField(
            model_name="homeslider",
            name="position",
            field=models.CharField(
                choices=[
                    ("top", "بالای صفحه (قبل از Hero)"),
                    ("after_hero", "بعد از Hero Section"),
                    ("after_stats", "بعد از Stats Section"),
                    ("custom", "موقعیت سفارشی (بر اساس order)"),
                ],
                default="top",
                help_text="جای قرار گرفتن اسلایدر در صفحه هوم",
                max_length=20,
                verbose_name="موقعیت اسلایدر",
            ),
        ),
        migrations.AlterField(
            model_name="homeslider",
            name="aspect_ratio",
            field=models.CharField(
                default="21/9", help_text="مثل 16/9 یا 21/9", max_length=10
            ),
        ),
    ]
