# Generated by Django 5.2.4 on 2025-12-02 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("siteconfig", "0011_homeslider_custom_order_homeslider_position_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="homeslider",
            name="height_desktop",
            field=models.PositiveIntegerField(
                default=480,
                help_text="مثلاً 480 یا 600",
                verbose_name="ارتفاع دسکتاپ (px)",
            ),
        ),
        migrations.AddField(
            model_name="homeslider",
            name="height_mobile",
            field=models.PositiveIntegerField(
                default=260,
                help_text="مثلاً 220 یا 280",
                verbose_name="ارتفاع موبایل (px)",
            ),
        ),
        migrations.AddField(
            model_name="homeslider",
            name="max_width",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="اختیاری؛ اگر پر شود، اسلایدر در مرکز با این حداکثر عرض نمایش داده می\u200cشود",
                null=True,
                verbose_name="حداکثر عرض (px)",
            ),
        ),
        migrations.AddField(
            model_name="homeslider",
            name="use_custom_size",
            field=models.BooleanField(
                default=False,
                help_text="اگر فعال باشد از ارتفاع\u200cهای ثابت به\u200cجای نسبت تصویر استفاده می\u200cشود",
                verbose_name="سایزبندی دستی",
            ),
        ),
        migrations.AlterField(
            model_name="homeslider",
            name="aspect_ratio",
            field=models.CharField(
                default="21/9",
                help_text="مثل 16/9 یا 21/9",
                max_length=10,
                verbose_name="نسبت تصویر (در صورت غیرفعال بودن سایزبندی دستی)",
            ),
        ),
    ]
