# Generated by Django 5.2.4 on 2025-12-04 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "siteconfig",
            "0012_homeslider_height_desktop_homeslider_height_mobile_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="SocialLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50, verbose_name="عنوان")),
                ("url", models.CharField(max_length=300, verbose_name="لینک")),
                (
                    "icon_class",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="مثلاً: fab fa-instagram، fab fa-telegram، fab fa-whatsapp",
                        max_length=80,
                        verbose_name="کلاس آیکون (FontAwesome)",
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        choices=[
                            ("contact", "صفحه تماس"),
                            ("header", "هدر"),
                            ("footer", "فوتر"),
                        ],
                        default="contact",
                        max_length=20,
                        verbose_name="محل نمایش",
                    ),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(default=0, verbose_name="ترتیب"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="فعال")),
            ],
            options={
                "verbose_name": "لینک شبکه اجتماعی",
                "verbose_name_plural": "لینک\u200cهای شبکه اجتماعی",
                "ordering": ["order", "id"],
            },
        ),
    ]
